DROP TABLE MEMBER CASCADE CONSTRAINTS; --테이블이 다른 테이블에 참조되어있어도 지운다.
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE LIBRARY CASCADE CONSTRAINTS;
DROP SEQUENCE BOOK_ID_SEQ;
DROP SEQUENCE comment_seq;


CREATE TABLE MEMBER(--회원 관리를 위한 테이블
ID VARCHAR2(10) PRIMARY KEY, --ID
PASS VARCHAR2(15) NOT NULL, --PASSWORD
NAME VARCHAR2(10CHAR) NOT NULL --이름
);


create sequence book_id_seq start with 0 minvalue 0;
create sequence comment_seq start with 0 minvalue 0;

CREATE TABLE BOOK( --책 정보를 담기 위한 테이블
BOOK_ID VARCHAR2(10) PRIMARY KEY, --시퀀스
NAME VARCHAR2(30CHAR) NOT NULL, --제목
HIT NUMBER NOT NULL, --조회수
KIND VARCHAR2(3) NOT NULL, --책 종류
IMAGE_NAME VARCHAR2(50CHAR) NOT NULL, --이미지 이름
AUTHOR VARCHAR2(20CHAR) NOT NULL, --저자 이름
LIST VARCHAR2(300CHAR), --목차
INTRODUCE VARCHAR2(300CHAR), --소개
AUTHOR_INTRODUCE VARCHAR2(300CHAR), --저자소개
BOOK_FOLDER VARCHAR2(30CHAR), --책(html 및 jpg)가 담긴 폴더 명
BOOK_PAGE NUMBER--책의 총 페이지 수
);
--lit이라면 '문학'장르
--edu라면 '교육'장르
--pol이라면 '정치'장르
--eco라면 '경제'장르
--kid라면 '어린이 장르-




CREATE TABLE LIBRARY(--내서재 정보를 담기위한 테이블
ID VARCHAR2(10) NOT NULL, --ID
BOOK_ID VARCHAR2(10), --책 ID
BOOK_MARK NUMBER,
FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON DELETE CASCADE, -- 참조하고 있는 MEMBER(ID)가 삭제되면 같이 삭제
FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE, --참조하고 있는 BOOK(BOOK_ID)가 삭제되면 같이 삭제
CONSTRAINT RENT PRIMARY KEY (ID, BOOK_ID)   
);



CREATE TABLE COMMENT_USER(
comment_id VARCHAR2(10) primary key,
ID VARCHAR2(10) NOT NULL, --ID
BOOK_ID VARCHAR2(10) NOT NULL, --책 ID
ment VARCHAR2(100CHAR),
inputday date default sysdate,
FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON DELETE CASCADE, -- 참조하고 있는 MEMBER(ID)가 삭제되면 같이 삭제
FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE --참조하고 있는 BOOK(BOOK_ID)가 삭제되면 같이 삭제
);



